config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :covid_photos
  resources :photo_usages
  get 'home/index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'home#index'
end

app/models/covid_photo.rb
class CovidPhoto < ApplicationRecord
  has_and_belongs_to_many :topics
  has_one_attached :photo
  belongs_to :user

  validates :date_taken, :location, :author_first, :author_last, :information,
            :topics, :photo, :submit_name, :submit_email, presence: true
  validates_presence_of :other_topic, if: :other_checked?

  def other_checked?
    topics.each do |t|
      return true if t.name == 'Other'
    end

    false
  end

  def copy_file(file_path)
    file_path << '/' unless file_path.end_with?('/)')
    photo.open do |file|
      FileUtils.cp file.path, "#{file_path}#{file_name}"
    end
    photo
  end

  def self.to_csv
    headers = %w[
      FileName
      Date
      Location
      Firstname
      Lastname
      Information
      Topics
      OtherTopics
      SubmitName
      SubmitEmail
      UserID
    ]
    attributes = %w[
      file_name
      date_taken
      location
      author_first
      author_last
      information
      topics_list
      other_topic
      submit_name
      submit_email
      user_uid
    ]
    CSV.generate(headers: true) do |csv|
      csv << headers
      all.each do |photo|
        csv << attributes.map{ |attr| photo.send(attr) }
      end
    end
  end

  def user_uid
    "#{user.uid}"
  end

  def topics_list
    "#{topics.map(&:name).join(', ')}"
  end

  def file_name
    "#{[photo.id, '--', photo.blob.filename].join}"
  end
end

app/controllers/covid_photos_controller.rb
class CovidPhotosController < ApplicationController
  before_action :set_covid_photo, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :new]

  include Pagy::Backend

  # GET /covid_photos
  # GET /covid_photos.json
  def index
    @q = CovidPhoto.ransack(params[:q])
    @all_covid_photos = @q.result
    @pagy, @covid_photos = pagy(@all_covid_photos)

    respond_to do |format|
      format.html
      format.csv { send_data @all_covid_photos.to_csv, filename: "covid-photos-export-#{Date.today}.csv"}
    end
  end

  # GET /covid_photos/1
  # GET /covid_photos/1.json
  def show
    authorize @covid_photo
  end

  # GET /covid_photos/new
  def new
    @covid_photo = CovidPhoto.new
    authorize @covid_photo
  end

  # GET /covid_photos/1/edit
  def edit
    authorize @covid_photo
  end

  # POST /covid_photos
  # POST /covid_photos.json
  def create
    @covid_photo = CovidPhoto.new(covid_photo_params)
    @covid_photo.user = current_user

    respond_to do |format|
      if @covid_photo.save
        format.html { redirect_to @covid_photo, notice: 'Thank you for your submission!' }
        format.json { render :show, status: :created, location: @covid_photo }
      else
        format.html { render :new }
        format.json { render json: @covid_photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /covid_photos/1
  # PATCH/PUT /covid_photos/1.json
  def update
    respond_to do |format|
      if @covid_photo.update(covid_photo_params)
        format.html { redirect_to @covid_photo, notice: 'Covid photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @covid_photo }
      else
        format.html { render :edit }
        format.json { render json: @covid_photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /covid_photos/1
  # DELETE /covid_photos/1.json
  def destroy
    authorize @covid_photo
    @covid_photo.destroy
    respond_to do |format|
      format.html { redirect_to covid_photos_url, notice: 'Covid photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_covid_photo
    @covid_photo = CovidPhoto.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def covid_photo_params
    params.require(:covid_photo).permit(:date_taken, :location, :author_first, :author_last, :information, :submit_name, :submit_email, :other_topic, :photo, topic_ids: [])
  end
end

app/helpers/covid_photos_helper.rb
module CovidPhotosHelper
  include Pagy::Frontend
  def other_display(topic_ids)
    return 'style=display:none;' unless topic_ids.include? Topic.last.id
  end
end

app/views/covid_photos/_form.html.erb
<%= javascript_pack_tag 'covid_photos' %>
<%= form_with(model: covid_photo, local: true, validate: true) do |form| %>
  <% if covid_photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(covid_photo.errors.count, "error") %> prohibited this covid_photo from being saved:</h2>

      <ul>
        <% covid_photo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="rvt-box rvt-m-top-md">
    <div class="rvt-box__header">
       Images Information
    </div>
    <div class="field rvt-box__body">
      <div class="field rvt-m-top-md">
        <%= form.label :date_taken, class: 'required'  %>
        <div id="covid-date-field">
          <%= form.date_select :date_taken, order: [:month, :day, :year], start_year: 2019, end_year: 2022 %>
        </div>
      </div>

      <div class="field rvt-m-top-md">
        <%= form.label :location, class: 'required' %>
        <%= form.text_field :location, placeholder: true %>
      </div>

      <div class="rvt-m-top-md">
        <%= form.label :author %>
      </div>

      <div class="rvt-grid">
        <div class="field  rvt-grid__item">
          <%= form.label :author_first, class: 'required' %>
          <%= form.text_field :author_first, placeholder: true %>
        </div>

        <div class="field  rvt-grid__item">
          <%= form.label :author_last, class: 'required' %>
          <%= form.text_field :author_last, placeholder: true %>
        </div>
      </div>

      <div class="field rvt-m-top-md rvt-grid__item">
        <%= form.label :information, class: 'required' %>
        <%= form.text_area :information, placeholder: true %>
      </div>

      <div class="field rvt-m-top-md">
        <%= form.label :topics, class: 'required' %>
        <ul class="rvt-plain-list">
        <%= form.collection_check_boxes :topic_ids, Topic.all, :id, :name do |m| %>
          <li>
            <%= m.check_box %> <%= m.label %>
          </li>
        <% end %>
        </ul>
      </div>

      <div id="other-topic_div" class="field rvt-m-top-md" <%= other_display(covid_photo.topic_ids) %>>
        <%= form.label :other_topic %>
        <%= form.text_field :other_topic %>
      </div>
    </div>
  </div>

  <div class="rvt-box rvt-m-top-md">
    <div class="rvt-box__header">
      Upload File
    </div>
    <div class="rvt-box__body">
      <div class="rvt-file" data-upload="covid_photo_photo">
        <%= form.file_field :photo,  'aria-describedby': 'file-description' %>
        <label for="covid_photo_photo" class="rvt-button">
            <span>Upload a file*</span>
            <svg aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
                <path fill="currentColor" d="M10.41,1H3.5A1.3,1.3,0,0,0,2.2,2.3V13.7A1.3,1.3,0,0,0,3.5,15h9a1.3,1.3,0,0,0,1.3-1.3V4.39ZM11.8,5.21V6H9.25V3h.34ZM4.2,13V3h3V6.75A1.25,1.25,0,0,0,8.5,8h3.3v5Z"/>
            </svg>
        </label>
        <div class="rvt-file__preview" data-file-preview="covid_photo_photo" id="file-description">
            No file selected
        </div>
      </div>
    </div>
  </div>

  <div class="rvt-box rvt-m-top-md">
    <div class="rvt-box__header">
       IUPUI University Library Publishing Agreement
    </div>
    <div class="rvt-box__body">
      <p>
        In order for IUPUI University Library to reproduce, translate, and
        distribute your submission worldwide, your agreement to the following
        terms is necessary.
      </p>
      <p>
        By signing and submitting this license, you (the creator or copyright
        owner)grant to Indiana University Board of Trustees on behalf of IUPUI
        a non-exclusive, perpetual, irrevocable right to reproduce, translate
        (as defined below), and/or distribute your submission worldwide in
        print and electronic format and in any medium, including but not
        limited to audio or video.
      </p>
      <p>
        You agree that IUPUI may, without changing the content, translate the
        submission to any medium or format, now known or later developed, for
        preservation or access, and provide basic metadata that describes the
        contents for discovery.
      </p>
      <p>
        You also agree that IUPUI may keep more than one copy of this submission
        for security, back-up and preservation.
      </p>
      <p>
        You represent that the submission is your original work, and that you
        have the right to grant the rights contained in this license. You also
        represent that your submission does not, to the best of your knowledge,
        infringe upon anyone's copyright.
      </p>
      <p>
        If the submission contains material for which you do not hold copyright,
        you represent that you have obtained the unrestricted permission of the
        copyright owner to grant IUPUI the rights required by this license, and
        that such third-party owned material is clearly identified and
        acknowledged within the text or content of the submission.
      </p>
      <p>
        If the submission is based upon work that has been sponsored or
        supported by an agency or organization other than Indiana University,
        you represent that you have fulfilled any right of review or other
        obligations required by such contract or agreement.
      </p>
      <p>
        IUPUI University Library will clearly identify your name as the creator
        and/or copyright owner of the submission, and will not make any
        alterations, other than as allowed by this license, to your submission.
      </p>
      <p>
        IUPUI University Library reserves the right to remove submissions that
        do not fit within the scope of this collection.​
      </p>

      <div class="rvt-grid">
        <div class="field rvt-m-top-md rvt-grid__item">
          <%= form.label "Name", class: 'required' %>
          <%= form.text_field :submit_name %>
        </div>

        <div class="field rvt-m-top-md rvt-grid__item">
          <%= form.label "Email", class: 'required' %>
          <%= form.text_field :submit_email %>
        </div>
      </div>
    </div>
  </div>

  <div>
    <p><strong>* Required Fields</strong></p>
  </div>

  <div class="actions rvt-m-top-md">
    <%= form.submit "Submit", class: "rvt-button" %>
  </div>
<% end %>

app/views/covid_photos/_index_admin.html.erb
<div id="covid-filters">
  <div class="rvt-box">
    <div class="rvt-box__header">
      Filters
    </div>
    <div class="rvt-box__body">
      <%= search_form_for @q do |f| %>
      <div class="rvt-grid">
        <div class="rvt-grid__item-md">
          <%= f.label 'Submitter' %>
          <%= f.search_field :user_uid_eq %>
        </div>
        <div class="rvt-grid__item-md">
          <%= f.label 'Date (or newer)' %>
          <%= f.search_field :date_taken_gteq %>
        </div>
        <div class="rvt-grid__item-md">
          <%= f.label 'Topic' %>
          <%= f.select :topics_name_cont, options_from_collection_for_select(Topic.all, 'name', 'name'), include_blank: true %>
        </div>
        <div class="rvt-grid__item">
          <%= f.submit "Filter", class: "rvt-button rvt-m-top-md" %>
          <%= link_to 'Reset', covid_photos_path, class: 'rvt-button rvt-button--secondary rvt-m-top-md' %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

<table>
  <thead>
    <tr>
      <th>Photo</th>
      <th><%= sort_link(@q, :date_taken, 'Date') %></th>
      <th><%= sort_link(@q, 'user_uid', 'Submitter') %></th>
      <th><%= sort_link(@q, :location, 'Where') %></th>
      <th><%= sort_link(@q, :author_last, 'Who') %></th>
      <th><%= t('Topics') %></th>
      <th><%= I18n.t 'helpers.label.covid_photo.other_topic' %></th>
    </tr>
  </thead>

  <tbody>
    <% @covid_photos.each do |covid_photo| %>
      <tr>
        <td>
          <%= link_to image_tag(covid_photo.photo.variant(resize_to_limit: [50, 50])), covid_photo, class: 'cp_index_photo' %>
        </td>
        <td><%= covid_photo.date_taken %></td>
        <td><%= covid_photo.user.uid %></td>
        <td><%= covid_photo.location %></td>
        <td><%= "#{covid_photo.author_last}, #{covid_photo.author_first}" %></td>
        <td><%= covid_photo.topics.map(&:name).join(", ") %></td>
        <td><%= covid_photo.other_topic %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br/>

<div>
  <%= link_to covid_photos_path(request.parameters.merge({format: :csv})), class: 'rvt-button' do %>
    <%= fa_icon 'download', text: '&nbsp; Export Data'.html_safe %>
  <% end %>
</div>


<div class="rvt-m-top-md">
  <%== pagy_info(@pagy) %>
  <%== render '/pagy/nav', locals: {pagy: @pagy} %>
</div>

<br/>

<%= link_to 'New Covid Photo', new_covid_photo_path, class: 'rvt-button rvt-button__primary' %>

app/views/covid_photos/_index_default.html.erb
<div>
  <p>
    The IUPUI University Library is collecting digital images from anyone
    affiliated with the IUPUI-campus (students, staff, faculty) for the creation
    of the digital collection "IUPUI Community: Documenting Life During the
    Pandemic." This collection aims to document the impact that the Coronavirus
    pandemic has made to our daily lives. By sharing your images, you can help
    shape how future generations will understand these events.
  </p>
</div>

<div class="rvt-box rvt-m-bottom-md">
  <div class="rvt-box__header">
     Images content guidelines
  </div>
  <div class="rvt-box__body">
    <p>What are we looking for?</p>
    <p>
      Photographs or screenshots documenting the following topics:
      <ul>
        <li>Working or attending classes remotely</li>
        <li>Interacting with others (practicing social distancing)</li>
        <li>Changes in the environment that surrounds you</li>
      </ul>
    </p>
    <p>
      Images submitted will undergo a review process and will be added to the
      collection if approved. The collection will eventually become part of
      <a href="https://ulib.iupui.edu/collections">
        University Library’s publicly accessible digital collections
      </a>.
      Submitting an image does not guarantee inclusion in the collection.
    </p>
  </div>
</div>

<%= link_to "Submit Photo", new_covid_photo_path, class: "rvt-button rvt-button--primary" %>

app/views/covid_photos/edit.html.erb
<h1>Editing Covid Photo</h1>

<%= render 'form', covid_photo: @covid_photo %>

<%= link_to 'Show', @covid_photo %> |
<%= link_to 'Back', covid_photos_path %>

app/views/covid_photos/index.html.erb
<h1>COVID-19 Digital Collection Project</h1>

<% if current_user && current_user.admin? %>
  <%= render "index_admin" %>
<% else %>
  <%= render partial: "index_default" %>
<% end %>

app/views/covid_photos/new.html.erb
<h1 class="rvt-m-top-md">COVID-19 Digital Collection Project Submission Form</h1>

<% if current_user %>
  <%= render 'form', covid_photo: @covid_photo %>
<% else %>
  <div>
    <p>Please authenticate before submitting photo.</p>
    <%= link_to "IU Login", user_cas_omniauth_authorize_path, class: "rvt-button rvt-button--primary", method: :post %>
  </div>
<% end %>

app/views/covid_photos/show.html.erb
<h1>COVID-19 Digital Collection Project</h1>
<h2><%= "Submission ID: #{@covid_photo.id}" %></h2>
<p>
  <a href="<%= rails_blob_url(@covid_photo.photo) %>">
    <%= image_tag @covid_photo.photo.variant(resize_to_limit: [200, 200]) %>
  </a>
</p>
<table id="covid-photo-table" class="rvt-table-stripes">
  <caption class="sr-only">Covid Photo Information</caption>
  <tbody>
    <tr>
      <th><%= I18n.t 'helpers.label.covid_photo.date_taken' %></th>
      <td><%= @covid_photo.date_taken %></td>
    </tr>
    <tr>
      <th><%= I18n.t 'helpers.label.covid_photo.location' %></th>
      <td><%= @covid_photo.location %></td>
    </tr>
    <tr>
      <th><%= I18n.t 'helpers.label.covid_photo.author' %></th>
      <td><%= "#{@covid_photo.author_last}, #{@covid_photo.author_first}" %></td>
    </tr>
    <tr>
      <th><%= I18n.t 'helpers.label.covid_photo.information' %></th>
      <td><%= @covid_photo.information %></td>
    </tr>
    <tr>
      <th><%= I18n.t 'helpers.label.covid_photo.topics' %></th>
      <td>
        <ul>
        <% @covid_photo.topics.each do |t| %>
          <li><%= t.name %></li>
        <% end %>
        </ul>
      </td>
    </tr>
    <tr>
      <th><%= I18n.t 'helpers.label.covid_photo.other_topic' %></th>
      <td><%= @covid_photo.other_topic %></td>
    </tr>
    <tr>
      <th>Signature</th>
      <td><%= @covid_photo.submit_name %> (<%= @covid_photo.submit_email %>)</td>
    </tr>
  </tbody>
</table>

<div class="rvt-p-top-md">
  <% if current_user && current_user.admin? %>
    <%= link_to 'Edit', edit_covid_photo_path(@covid_photo), class: 'rvt-button' %>
    <%= link_to 'Destroy', @covid_photo, method: :delete, data: { confirm: 'Are you sure?' }, class: 'rvt-button rvt-button--secondary' %>
  <% else %>
    <%= link_to 'Submit Another Photo', new_covid_photo_path(), class: "rvt-button rvt-button__primary" %>
  <% end %>
</div>