config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :covid_photos
  resources :photo_usages
  get 'home/index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'home#index'
end

app/models/photo_usage.rb
class PhotoUsage < ApplicationRecord
  has_one_attached :photo
  has_one_attached :cv_upload
  belongs_to :user
  belongs_to :user_role
  belongs_to :school

  validates :signature, presence: true
  validates :acknowledgement, acceptance: true
  validates :photo, attached: true, if: :alt_photo?

  def alt_photo?
    wikimedia_permission == "no"
  end

end

app/controllers/photo_usages_controller.rb
class PhotoUsagesController < ApplicationController
  before_action :set_photo_usage, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :new]

  include Pagy::Backend

  # GET /photo_usages
  # GET /photo_usages.csv
  def index
    @q = PhotoUsage.ransack(params[:q])
    @all_photo_usages = @q.result
    @pagy, @photo_usages = pagy(@all_photo_usages)
  end

  # GET /photo_usage/1
  # GET /photo_usage/1.json
  def show
    authorize @photo_usage
  end

  # GET /photo_usage/new
  def new
    @photo_usage = PhotoUsage.new
    authorize @photo_usage
  end

  # GET /covid_photos/1/edit
  def edit
    authorize @photo_usage
  end

  # POST /photo_usages
  # POST /photo_usages.json
  def create
    @photo_usage = PhotoUsage.new(photo_usage_params)
    @photo_usage.user = current_user
    respond_to do |format|
      if @photo_usage.save
        format.html { redirect_to @photo_usage, notice: 'Thank you for your submission!' }
        format.json { render :show, status: :created, location: @photo_usage }
      else
        format.html { render :new }
        format.json { render json: @photo_usage.errors, status: :unprocessable_entity }
      end
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_photo_usage
    @photo_usage = PhotoUsage.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def photo_usage_params
    params.require(:photo_usage).permit(:wikimedia_permission, :user_role_id, :acknowledgement, :signature, :cv_upload, :school_id, :photo )
  end
end

app/helpers/photo_usage_helper.rb
module PhotoUsageHelper
end

app/views/photo_usages/_form.html.erb
<%= javascript_pack_tag 'photo_usages' %>
<%= form_with(model: photo_usage, local: true, validate: true, id: 'photo_usage_form') do |form| %>
  <% if photo_usage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo_usage.errors.count, "error") %> prohibited this form from being saved:</h2>

      <ul>
        <% photo_usage.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="rvt-box rvt-m-top-md">
    <div class="rvt-box__header">
       Photo Usage Permission
    </div>
    <div class="field rvt-box__body">
      <fieldset class='rvt-p-bottom-md'>
        <%= form.label :user_role, class: 'required' %>
        <%= form.collection_select :user_role_id, UserRole.all, :id, :name, include_blank: "Select Role..." %>

        <%= form.label :school, class: 'required' %>
        <%= form.collection_select :school_id, School.all.order(:name), :id, :name, include_blank: "Select School/Unit..." %>
      </fieldset>

      <fieldset class='rvt-p-bottom-md'>
        <legend class='required bold'>
          Can we use the picture from your school or unit profile page to contribute it to
          <a href="https://commons.wikimedia.org/wiki/Main_Page">Wikimedia Commons</a>?
        </legend>
        <ul class="rvt-plain-list">
          <li>
            <%= form.radio_button :wikimedia_permission, 'yes', id: 'wikimedia_permission_yes', checked: true %>
            <label for='wikimedia_permission_yes'>Yes - use school/unit profile photo</label>
          </li>
          <li>
            <%= form.radio_button :wikimedia_permission, 'no', id: 'wikimedia_permission_no' %>
            <label for='wikimedia_permission_no'>No - I prefer to upload my own photo</label>
          </li>
        </ul>
        <div id='alt_photo' <% if @photo_usage[:wikimedia_permission] != 'no' %>style="display:none;" <% end %>>
          <p class="required bold">
            If you prefer to share a different picture,
            click on the "Upload a Photo" button to upload it
          </p>

          <div id='own_photo'>
            <div class="rvt-file" data-upload="photo_usage_photo">
              <%= form.file_field :photo, accept: 'image/png,image/gif,image/jpeg,image/jpg', 'aria-describedby': 'photo-file-description' %>
              <label for="photo_usage_photo" class="rvt-button">
                  <span>Upload a Photo</span>
                  <svg aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
                      <path fill="currentColor" d="M10.41,1H3.5A1.3,1.3,0,0,0,2.2,2.3V13.7A1.3,1.3,0,0,0,3.5,15h9a1.3,1.3,0,0,0,1.3-1.3V4.39ZM11.8,5.21V6H9.25V3h.34ZM4.2,13V3h3V6.75A1.25,1.25,0,0,0,8.5,8h3.3v5Z"/>
                  </svg>
              </label>
              <div class="rvt-file__preview" data-file-preview="photo_usage_photo" id="photo-file-description">
                  No file selected
              </div>
            </div>
            <div class="file-types">
              Allowed file types: jpg, jpeg, png, gif
            </div>
            <div id='own_photo_message'>
            </div>
          </div>

        </div>
      </fieldset>

      <fieldset class="rvt-p-bottom-md">
        <p class="bold">
          Upload the latest version of your CV for us to improve your scholarly profile
        </p>

        <div class="rvt-file" data-upload="photo_usage_cv_upload">
          <%= form.file_field :cv_upload,
                accept: 'application/pdf,
                         application/msword,
                         application/vnd.openxmlformats-officedocument.wordprocessingml.document,
                         application/vnd.oasis.opendocument.text,
                         text/plain',
                multiple: false,
                'aria-describedby': 'cv-upload-file-description' %>
          <label for="photo_usage_cv_upload" class="rvt-button">
              <span>Upload a CV</span>
              <svg aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
                  <path fill="currentColor" d="M10.41,1H3.5A1.3,1.3,0,0,0,2.2,2.3V13.7A1.3,1.3,0,0,0,3.5,15h9a1.3,1.3,0,0,0,1.3-1.3V4.39ZM11.8,5.21V6H9.25V3h.34ZM4.2,13V3h3V6.75A1.25,1.25,0,0,0,8.5,8h3.3v5Z"/>
              </svg>
          </label>
          <div class="rvt-file__preview" data-file-preview="photo_usage_photos" id="cv-upload-file-description">
              No file selected
          </div>
        </div>
        <div class="file-types">
          Allowed file types: pdf, doc, docx, odt, txt
        </div>

      </fieldset>

      <fieldset class='rvt-p-bottom-md'>
        <p class="bold">
          In order to use your image for this project it must have a
          Creative Commons Attribution-Share Alike License (CC-BY-SA).
          By checking this box I grant this image a CC-BY-SA license.
          For more information on Creative Commons and the types of licenses,
          please visit the
          <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.en" target="_blank">
            Creative Commons website
          </a>.
        </p>
        <ul class="rvt-inline-list">
          <li class="rvt-checkbox-wrapper">
            <%= form.check_box :acknowledgement, validate: true %>
            <%= form.label :acknowledgement, class: 'required' %>
          </li>
        </ul>
        <%= form.label :signature, class: 'required' %>
        <%= form.text_field :signature %>
      </fieldset>
    </div>
  </div>

  <div>
    <p><strong>* Required Fields</strong></p>
  </div>

  <div class="actions rvt-m-top-md">
    <%= form.submit "Submit", class: "rvt-button" %>
  </div>
<% end %>

app/views/photo_usages/_index_admin.html.erb
<div id="photo-usage-filters">
  <div class="rvt-box">
    <div class="rvt-box__header">
      Filters
    </div>
    <div class="rvt-box__body">
      <%= search_form_for @q do |f| %>
      <div class="rvt-grid">
        <div class="rvt-grid__item-md">
          <%= f.label 'Submitter' %>
          <%= f.search_field :user_uid_eq %>
        </div>
        <div class="rvt-grid__item-md">
          <%= f.label 'School/Unit' %>
          <%= f.select :school_id_eq, options_from_collection_for_select(School.all.order(:name), 'id', 'name'), include_blank: true %>
        </div>
        <div class="rvt-grid__item">
          <%= f.submit "Filter", class: "rvt-button rvt-m-top-md" %>
          <%= link_to 'Reset', photo_usages_path, class: 'rvt-button rvt-button--secondary rvt-m-top-md' %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

<table>
  <thead>
    <tr>
      <th>User ID</th>
      <th>Role</th>
      <th>School/Unit</th>
      <th>Wiki Permission</th>
    </tr>
  </thead>

  <tbody>
    <% @photo_usages.each do |photo_usage| %>
      <tr>
        <td><%= photo_usage.user.uid %></td>
        <td><%= photo_usage.user_role.name %></td>
        <td><%= photo_usage.school.name %></td>
        <td><%= photo_usage.wikimedia_permission %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New Photo Usage and CV Form", new_photo_usage_path, class: "rvt-button rvt-button--primary" %>

app/views/photo_usages/_index_default.html.erb
<div>
  <p>
    The library needs your help to update your scholarly profile in Scholia.
  </p>
  <p>
    The IUPUI University Library has been making contributions to Wikidata
    since 2017 in an effort to expand the representation of IUPUI scholars.
    The library formalized this process by developing and implementing the
    Scholarly Profiles as Service (SPaS). This service leverages Wikidata to
    provide global exposure and reach to IUPUI scholars and their research,
    and leans on Scholia, an open-source web-service that feeds from Wikidata,
    to generate the scholarly profiles. With this work, we are increasing the
    visibility of IUPUI-affiliated scholars and their publications in an
    environment that is openly accessible to all.
  </p>
</div>

<div class="rvt-box rvt-m-bottom-md">
  <div class="rvt-box__header">
     How can you help us improve your profile in Scholia?
  </div>
  <div class="rvt-box__body">
    <ul>
      <li>
        Grant the library permission to use your existing image (from your
        school’s/unit’s webpage) or upload a new picture you have the rights to.
        If uploading a new picture, make sure it is one you took of yourself.
      </li>
      <li>
        Upload your latest CV so we can use it to have the most up-to-date
        publication data reflected in Scholia.
      </li>
  </div>
</div>

<%= link_to "Submit Photo Usage and CV Form", new_photo_usage_path, class: "rvt-button rvt-button--primary" %>

app/views/photo_usages/edit.html.erb
<h1>Editing Photo Usage</h1>

<%= render 'form', photo_usage: @photo_usage %>

<%= link_to 'Show', @photo_usage %> |
<%= link_to 'Back', photo_usages_path %>

app/views/photo_usages/index.html.erb
<h1>Photo Usage & CV Form</h1>

<% if current_user && current_user.admin? %>
  <%= render "index_admin" %>
<% else %>
  <%= render partial: "index_default" %>
<% end %>

app/views/photo_usages/new.html.erb
<h1 class="rvt-m-top-md">Photo Usage and CV Form</h1>

<% if current_user %>
  <%= render 'form', photo_usage: @photo_usage %>
<% else %>
  <div>
    <p>Please authenticate before submitting a photo usage and cv form.</p>
    <%= link_to "IU Login", user_cas_omniauth_authorize_path, class: "rvt-button rvt-button--primary", method: :post %>
  </div>
<% end %>

app/views/photo_usages/show.html.erb
<h1>Photo Usage and CV Form</h1>
<h2><%= "Submission ID: #{@photo_usage.id}" %></h2>

<table id="photo-usage-table" class="rvt-table-stripes">
  <caption class="sr-only">Photo Usage and CV Information</caption>
  <tbody>
    <tr>
      <th><%= I18n.t 'helpers.label.photo_usage.user' %></th>
      <td><%= @photo_usage.user.uid %></td>
    </tr>
    <tr>
      <th><%= I18n.t 'helpers.label.photo_usage.user_role' %></th>
      <td><%= @photo_usage.user_role.name %></td>
    </tr>
    <tr>
      <th><%= I18n.t 'helpers.label.photo_usage.school' %></th>
      <td><%= @photo_usage.school.name %></td>
    </tr>
    <tr>
      <th><%= I18n.t 'helpers.label.photo_usage.acknowledgement' %></th>
      <td><%= @photo_usage.acknowledgement %></td>
    </tr>
    <tr>
      <th><%= I18n.t 'helpers.label.photo_usage.signature' %></th>
      <td><%= @photo_usage.signature %></td>
    </tr>
  </tbody>
</table>